### ISSUE TITLE
Add feature Service (e.g. MySQL)

### ISSUE THREAD

**Issue by edno** [edno/codeception-secureshell#2]
The feature 'Service' should allow to create tunnel for accessing remote services like MySQL (3306)

If define within the configuration, then the tunnel will be created before the suite.

Example of configuration:
```yaml
modules:
    enabled:
        - Codeception\Extension\SecureShell
    config:
        Codeception\Extension\SecureShell:
            - service:
                 server:
                 port:
                 mode:
                 auth:
                 redirect:
```

This feature implies that the module can handle multiple connections.
